<?php


/**
*
*/
function pp_jmstv_init() {
	// add JS
		drupal_set_html_head('<script type="text/javascript" src="http://piraten-mond.de/jmstvab18.js"></script> ');
}


/**
* Display help and module information.
* @param path
*   Which path of the site we're displaying help.
* @param arg
*   Array that holds the current path as would be returned from arg() function.
* @return
*   help text for the path.
*/
function pp_jmstv_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#pp_jmstv":
      $output = '<p>'. t("Fügt das notwendige Javascript in den Header ein.").'</p>';
      break;
  }
  return $output;
} // function pp_newsletter_help


/**
* Valid permissions for this module
* @return array An array of valid permissions for the pp_newsletter module
*/
function pp_jmstv_perm() {
  return array('access content');
} // function pp_newsletter_perm()


?>